alpha.tcp.host=127.0.0.1
alpha.tcp.port=5050
alpha.jms.brokerUrl=tcp://127.0.0.1:61616
alpha.jms.topic.monsters=alpha.game.monsters
alpha.jms.topic.events=alpha.game.events
alpha.jms.topic.winner=alpha.game.winner
alpha.game.boardRows=4
alpha.game.boardCols=4
alpha.game.targetScore=5
alpha.game.spawnIntervalMs=1500
alpha.game.restartDelayMs=2500
alpha.server.workerThreads=32
